name: CI/CD Workflow

on:
  pull_request:
  push:
    branches:
      - main
  
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
