name: Gitleaks Scan

on:
  push:
    branches:
      - main # o el nombre de tu rama principal

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Gitleaks
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/download/v7.5.0/gitleaks-linux-amd64
        chmod +x gitleaks-linux-amd64
        sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

    - name: Run Gitleaks
      run: gitleaks --verbose --depth=5
